### ISSUE TITLE
Bug/001/Synonym/Create

### ISSUE THREAD

**Issue by Kirisaki124** [DungltAPV/Virtual-HCM#25]
Điền chữ
Bấm tokenize
Tick
Xong tokenize lại từ khác cái tick vẫn còn

**Comment by Kirisaki124** [comment]
ở trong phần create synonyms nhaaaa

**Comment by hoakhuat** [comment]
Done nha

**Comment by LethDz** [comment]
t chưa xem mà đã close rồi :)))) @hoakhuat
