### ISSUE TITLE
Bug/004/Get reference in new knowledge data

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#30]
![image](https://user-images.githubusercontent.com/49860142/99262548-b723bf00-2850-11eb-8205-f146c6fb9383.png)
- Lấy được data sao lại để successAlert thế kia hả 👎

**Comment by LethDz** [comment]
sửa lại tên nút đi cái ở bên ngoài đã là new reference bên trong cũng thế
Thay icon của New Reference màu xanh bên ngoài thành quyển sách cũng được 👎

**Comment by Kirisaki124** [comment]
.
