### ISSUE TITLE
Bug/007/Create Button ở phần generate question 

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#33]
![image](https://user-images.githubusercontent.com/49860142/99267705-e0dfe480-2856-11eb-8259-17b18bb02569.png)
Khi mà generate lần 1 thì nó hiện View question đúng không. bấm vào Modal thì phải phần nút Create thành SAVE chứ với cả thêm icon save vào

**Comment by Kirisaki124** [comment]
.
