### ISSUE TITLE
Bug/008/When errorList state has a list of error -> cant send form

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#34]
![image](https://user-images.githubusercontent.com/49860142/99269115-919ab380-2858-11eb-848a-2749119ab7a2.png)
Trong phần new knowledge data khi mà submit form lỗi thì phải xóa errorList state thì mới gửi form tiếp được 
=> Đéo ai check như thế ???

**Comment by dungnm06** [comment]
.
