### ISSUE TITLE
Bug/009/Add Synonym for specific word 

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#35]
![image](https://user-images.githubusercontent.com/49860142/99272033-e4289f80-2859-11eb-9bb5-88378ffcfd48.png)

- Phần thêm synonym cho từ theo a dũng nói thì phải làm thêm 1 chức năng là khi tokenize word ra thì có thể sẽ có thể không theo ý mình. Như trên hình có từ Trên Messenger bị tách ra. Nhưng mà mình lại muốn add synonym cả hẳn cái cụm từ Trên Messenger thì làm sao ? 

=> Anh Dũng bảo phải làm thêm 1 cái nút gì gì đó để ghép cái từ 'messenger' với từ 'Trên' thành 1 từ 'Trên messenger'

**Comment by LethDz** [comment]
Có gì không hiểu hỏi lại a dũng

**Comment by dungnm06** [comment]
.
