### ISSUE TITLE
Bug/012/In Edit Knowledge Data When add more synonym for specific word

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#38]
![image](https://user-images.githubusercontent.com/49860142/99276914-c3634880-285f-11eb-96c6-36996ee56c11.png)

- Khi mà vào 1 knowledge data bất kì rồi thêm bộ từ đồng nghĩa cho 1 từ bất kì xong rồi submit form thì hiện ra lỗi

**Comment by dungnm06** [comment]
.
