### ISSUE TITLE
Bug/016/Create Knowledge Data phần subject

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#52]
![image](https://user-images.githubusercontent.com/49860142/100074892-dda9b180-2e71-11eb-9d25-2b529b1a87f8.png)

- Khi t đã tokenize raw data với từ "Chủ tịch Hồ Chí Minh" và nhập question thì nó sẽ hiện ra từ đã tokenize trong cái dropdown. Nhưng khi t cancel raw data rồi thay đổi từ "Chủ tịch Hồ Chí Minh" thành "Bác Hồ" thì từ "Chủ tịch Hồ Chí Minh" vẫn còn trong cái dropdown

**Comment by dungnm06** [comment]
Sống chung vứi lũ thoai :3

**Comment by Kirisaki124** [comment]
Done
