### ISSUE TITLE
Bug/017/Generated Question

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#53]
![image](https://user-images.githubusercontent.com/49860142/100076470-cff52b80-2e73-11eb-963e-d229feb2effc.png)
Cho cái modal to ra nhé ```javascript size="lg" ```

**Comment by dungnm06** [comment]
![image](https://user-images.githubusercontent.com/56249898/100082304-6c76f800-2e8b-11eb-89ba-79b4d5cb3d55.png)
Done
