### ISSUE TITLE
Bug/018/Coresponse dropdown

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#54]
![image](https://user-images.githubusercontent.com/49860142/100078900-9c67d080-2e76-11eb-8b0f-e145d5e24fbe.png)
Bỏ cái Yes/No type đi

**Comment by dungnm06** [comment]
![image](https://user-images.githubusercontent.com/56249898/100080598-5d8f4600-2e89-11eb-8262-3966763fb86e.png)
Done
