### ISSUE TITLE
Bug/019/Reference Document

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#55]
![image](https://user-images.githubusercontent.com/49860142/100079452-40ea1280-2e77-11eb-9090-bc5b7f6d7cf9.png)
- Khi nào người dùng chọn vào reference rồi thì mới enable nút lên ko chọn thì ẩn đi.
- Với cả để cái minimum value cho cái page là 1 đi 👎

**Comment by dungnm06** [comment]
![image](https://user-images.githubusercontent.com/56249898/100081302-36854400-2e8a-11eb-92a0-06ee0d0e9295.png)
Done
