### ISSUE TITLE
Bug/020/Correspone Type

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#56]
![image](https://user-images.githubusercontent.com/49860142/100080925-008b9400-2e79-11eb-876e-df448a8fc235.png)
- Nhìn trông nguệc thế

**Comment by dungnm06** [comment]
![image](https://user-images.githubusercontent.com/56249898/100086115-47d14f00-2e90-11eb-8714-b23690d43c26.png)
Done
