### ISSUE TITLE
Bug/021/Subject Button and Generate Button

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#57]
![image](https://user-images.githubusercontent.com/49860142/100081782-00d85f00-2e7a-11eb-988f-7e9aa1d9014b.png)

- Để Subject Button với Generate Button để thuộc tính block đi. Khi generate xong thì có button view thì cũng để block

**Comment by dungnm06** [comment]
![image](https://user-images.githubusercontent.com/56249898/100082719-ef984e00-2e8b-11eb-9699-0cda0fee4207.png)
Done
