### ISSUE TITLE
Bug/022/Error Alert when not choose type of question

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#58]
![image](https://user-images.githubusercontent.com/49860142/100085535-bb6a6080-2e7e-11eb-8967-6d2ef9ed8bd8.png)
- Phải hiển thị rõ lỗi khi choose type chứ, dùng cái toast mà t đã add ý đừng để cho nó di chuyển lên bất tiện.

**Comment by dungnm06** [comment]
DONE
