### ISSUE TITLE
Things need to be corrected

### ISSUE THREAD

**Issue by LethDz** [DungltAPV/Virtual-HCM#65]
Sửa cái ảnh ở Login thành ảnh khác.

Account List Page:
- Bỏ success alert khi load bảng thành công.
- Thêm double-click để vào detail.
- Sau khi edit xong user thì redirect về trang account.
- Thêm nút refresh table.

Train Data List Page:
- Bỏ success alert khi load bảng thành công.
- Thêm double-click để vào detail.
- Create xong Train Data List thì tắt modal đi.
- Sửa lại các chữ train data thành training data.
- Edit xong thì tắt modal đi :D

Manage Training Process:
- Nút Reload Model bỏ đi.

Knowledge Data Page:
- Bỏ success alert khi load bảng thành công.
- Phần User Review thì để nút Review với nút View all review thành button group đi thay icon vào.
- Phần review thì 3 nút để thành button group rồi thêm icon vào.
- Phần View all review load bảng bỏ load successful đi.
- Nút view detail thì chuyển thành primary và phải disable khi chưa có row nào được chọn.
- Phần review detail thì cóp cái style của report detail về mà chỉnh lại.
- Nút Cancel ở rawdata cách ra.
- Nút Edit Knowledge Chuyển thành nút save thay icon save và phải ở trên phần user review nhé.

Document Reference:
- Nút Edit ở trong document reference detail phải để thành save và thanh icon.
- Nút Create ở trong create new document reference thì phải thành nút info đi.
- Edit xong thì tắt modal.
- Create xong thì tắt modal.

Synonym:
- Synonym Detail modal cái phần modal title phải ghi rõ là Synonym Detail.
	- Đổi cái nút check tokenize word thành màu primary ở phần create modal cũng thế.
	- đổi nút save thành info ở phần modal create cũng thế đổi nút thành info.
- Edit xong thì tắt modal đi.
- Create xong thì tắt modal đi.

- Lưu ý: Phải clear state khi mà edit modal tắt đi.
- Làm delete với chuyển trạng thái các dữ liệu khác thì phải có confirm.

**Comment by Kirisaki124** [comment]
Done
