### ISSUE TITLE
Bug/032/Don't update number of approve after approving and then choose that knowledge data

### ISSUE THREAD

**Issue by hoakhuat** [DungltAPV/Virtual-HCM#96]
![test_!](https://user-images.githubusercontent.com/37390039/101933792-45505280-3c0f-11eb-98c4-c5b1a76c41e2.PNG)
![test_2](https://user-images.githubusercontent.com/37390039/101933835-539e6e80-3c0f-11eb-8ca3-a8a4284126fd.PNG)
![test_3](https://user-images.githubusercontent.com/37390039/101933862-58fbb900-3c0f-11eb-8f88-f42b955c20e9.PNG)
![test_4](https://user-images.githubusercontent.com/37390039/101933883-62852100-3c0f-11eb-9e51-fcce1815d65a.PNG)
![test_5](https://user-images.githubusercontent.com/37390039/101933895-6618a800-3c0f-11eb-8d2a-b14654244a65.PNG)
![test_6](https://user-images.githubusercontent.com/37390039/101933903-69139880-3c0f-11eb-8d68-16e56be799a4.PNG)

**Comment by hoakhuat** [comment]
The same bug with decline 
![test_7](https://user-images.githubusercontent.com/37390039/101935223-539f6e00-3c11-11eb-9315-de972fdb52a8.PNG)

**Comment by Kirisaki124** [comment]
Done
